version: '2'
exclude_patterns:
  - 'docs'
  - 'documentation'
  - 'dist'
  - '**/*.log'
  - '**/*.ico'
  - 'e2e/'
  - 'demo/assets/'
  - 'demo/typings.d.ts'
  - '**/*.spec.ts'
  - '**/karma.conf.js'
  - 'demo/polyfills.ts'
  - 'demo/test.ts'
plugins:
  csslint:
    enabled: true
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
  git-legal:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json